# prova1
#
/run/initialize
#
/gps/particle neutron

#rectangle plane source
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 0 0 5 m
/gps/pos/halfx 10. cm
/gps/pos/halfy 10. cm

/gps/ang/type planar
/gps/direction 0 0 -1

# power-law energy distr.
/gps/ene/type Pow
/gps/ene/min 0.01 eV
/gps/ene/max 10. GeV
/gps/ene/alpha -1.

# commands below are independent of gps
#
/analysis/setFileName prova1 
/analysis/h1/set 1 100 0.01 1000000000 eV
/analysis/h2/set 1 100 -5 5 m none linear 100 -5 5 m none linear 
/analysis/h2/set 4 120 0 360 deg none linear 100 -1 1 none none linear
#
#/control/execute vis.mac
#
/run/printProgress 100
#
/run/beamOn 1000




